[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#37474f"
blue = "#80d8ff"
cyan = "#18ffff"
green = "#69f0ae"
magenta = "#ea80fc"
red = "#ff5252"
white = "#ffffff"
yellow = "#ffeb3b"

[colors.cursor]
cursor = "#78909c"
text = "#192228"

[colors.dim]
black = "#091012"
blue = "#2196f3"
cyan = "#00acc1"
green = "#4caf50"
magenta = "#9c27b0"
red = "#e53935"
white = "#90a4ae"
yellow = "#f9a825"

[colors.normal]
black = "#192228"
blue = "#29b6f6"
cyan = "#26c6da"
green = "#81c784"
magenta = "#ba68c8"
red = "#ef5350"
white = "#eceff1"
yellow = "#fbc02d"

[colors.primary]
background = "#192228"
foreground = "#b0bec5"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Command"

[[keyboard.bindings]]
key = "N"
mods = "Command"

[keyboard.bindings.command]
args = ["-n", "/Applications/Alacritty.app"]
program = "open"

[mouse]
hide_when_typing = true

[window]
decorations = "full"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
